# Generated by Django 3.1.6 on 2021-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210515_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='what_is_it',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
