# Generated by Django 3.1.6 on 2021-06-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='okundu',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message')),
            ],
        ),
    ]
