# Generated by Django 3.1.6 on 2021-06-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
