# Generated by Django 3.1.6 on 2021-06-06 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_profile_sontarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='second_user',
        ),
        migrations.AddField(
            model_name='room',
            name='sayi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
