# Generated by Django 3.1.6 on 2021-06-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210607_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
