# Generated by Django 3.1.6 on 2021-06-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210607_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayi',
            name='say',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sayi',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
    ]
