# Generated by Django 3.1.6 on 2021-06-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210607_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sayi',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='sayi',
            field=models.ManyToManyField(to='chat.Sayi'),
        ),
    ]
