# Generated by Django 3.1.6 on 2021-06-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20210607_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_date',
            new_name='date',
        ),
    ]
